name: scez
channels:
  - anaconda
  - conda-forge
  - bioconda
dependencies:
  - python>=3.9,<=3.12
  - scanpy
  - python-igraph
  - leidenalg
  - anndata
  - scipy
  - scar
  - scikit-learn==1.2.2
  - matplotlib
  - ipykernel
  - mscorefonts
  - pip
  - pip:
      - numba
      - adpbulk
      - pydeseq2
      - adjustText
      - watermark
